/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConsultationIntake {
  'id' : string,
  'status' : Status,
  'skinConcerns' : Array<string>,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'goals' : string,
  'skinType' : string,
  'currentRoutine' : string,
  'consentGiven' : boolean,
  'photos' : Array<ExternalBlob>,
}
export type ExternalBlob = Uint8Array;
export interface ServicePlan {
  'id' : string,
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'isFree' : boolean,
  'priceUSD' : bigint,
}
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'reviewed' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getIntakeById' : ActorMethod<[string], [] | [ConsultationIntake]>,
  'getServicePlans' : ActorMethod<[], Array<ServicePlan>>,
  'listIntakes' : ActorMethod<[], Array<ConsultationIntake>>,
  'submitIntake' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      Array<ExternalBlob>,
      boolean,
    ],
    string
  >,
  'updateIntakeStatus' : ActorMethod<[string, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];