/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ConsultationIntake = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'skinConcerns' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'goals' : IDL.Text,
  'skinType' : IDL.Text,
  'currentRoutine' : IDL.Text,
  'consentGiven' : IDL.Bool,
  'photos' : IDL.Vec(ExternalBlob),
});
export const ServicePlan = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'priceUSD' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getIntakeById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ConsultationIntake)],
      ['query'],
    ),
  'getServicePlans' : IDL.Func([], [IDL.Vec(ServicePlan)], ['query']),
  'listIntakes' : IDL.Func([], [IDL.Vec(ConsultationIntake)], ['query']),
  'submitIntake' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'updateIntakeStatus' : IDL.Func([IDL.Text, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ConsultationIntake = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'skinConcerns' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'goals' : IDL.Text,
    'skinType' : IDL.Text,
    'currentRoutine' : IDL.Text,
    'consentGiven' : IDL.Bool,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const ServicePlan = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'priceUSD' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getIntakeById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ConsultationIntake)],
        ['query'],
      ),
    'getServicePlans' : IDL.Func([], [IDL.Vec(ServicePlan)], ['query']),
    'listIntakes' : IDL.Func([], [IDL.Vec(ConsultationIntake)], ['query']),
    'submitIntake' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'updateIntakeStatus' : IDL.Func([IDL.Text, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };